### ISSUE TITLE
AZERTY keyboard conflict with chat key

### ISSUE THREAD

**Issue by Exterminator921** [HappinessMP/issues#2] opened 2023-01-23 17:31 UTC
### Description of the problem

I'm french so i have an AZERTY keyboard, but when I press z to walk forward, it also starts the chat

### Reproduction steps

put you keyboard layout on azerty and then try to walk forward

### Operating system

Windows 11

**Comment by GTA-Lion** [comment] 2023-01-23 17:57
Thanks for reporting this issue. The issue is reproducible and will be fixed in the next version.

**Comment by GTA-Lion** [comment] 2023-02-21 16:14
The default chat key was changed to Y in last build. This should fix the problem.

**Closed as completed by GTA-Lion** 2023-02-21 16:14 UTC
Labels: bug
