### ISSUE TITLE
Various glyphs support in chat

### ISSUE THREAD

**Issue by HarGabt** [HappinessMP/issues#9] opened 2023-01-24 16:13 UTC
### What do you suggest?

Adding russian (cyrillic) along with any other languages support would be nice, so people wouldn't have to resort to basic latin glyphs in conversations

![изображение](https://user-images.githubusercontent.com/44652400/214346508-b2b62d87-ab97-4726-8bc0-48a4c6f883c8.png)

**Comment by GTA-Lion** [comment] 2023-01-26 21:18
Thanks for reporting this issue. The issue is reproducible and will be fixed in one of the next versions.

**Comment by GTA-Lion** [comment] 2023-01-28 10:05
The issue was fixed with the latest update.

![grafik](https://user-images.githubusercontent.com/16139574/215260400-3fe98f4a-fe90-44a8-a87a-f2f2e9e34060.png)

**Closed as completed by GTA-Lion** 2023-01-28 10:05 UTC
Labels: bug
